
-- Viden Analytics Schema

-- Table 1: Price History (Raw Data)
CREATE TABLE IF NOT EXISTS price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker TEXT NOT NULL,
    date DATE NOT NULL,
    price DOUBLE PRECISION,
    ma_50 DOUBLE PRECISION,
    ma_200 DOUBLE PRECISION,
    UNIQUE(ticker, date)
);

-- Table 2: Market Summary (Latest Status)
CREATE TABLE IF NOT EXISTS market_summary (
    ticker TEXT PRIMARY KEY,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    latest_price DOUBLE PRECISION,
    trend_status TEXT, -- 'Bullish', 'Bearish'
    volatility_score DOUBLE PRECISION
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_price_history_ticker ON price_history(ticker);
CREATE INDEX IF NOT EXISTS idx_price_history_date ON price_history(date);

-- RLS Policies (Optional but recommended)
ALTER TABLE price_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE market_summary ENABLE ROW LEVEL SECURITY;

-- Allow read access to everyone (public app)
CREATE POLICY "Allow public read on price_history" ON price_history FOR SELECT USING (true);
CREATE POLICY "Allow public read on market_summary" ON market_summary FOR SELECT USING (true);

-- Allow service_role (and authenticated users if needed) to write
-- Note: Service role bypasses RLS anyway, but good to have explicit policy if we use other roles
CREATE POLICY "Allow service insert" ON price_history FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow service update" ON price_history FOR UPDATE USING (true);
