
import os
import pandas as pd
import psycopg
from psycopg import sql

# Configuration
# Using Supabase Connection Pooler
DB_HOST = "aws-0-us-east-1.pooler.supabase.com"  # Common pooler host
DB_NAME = "postgres"
DB_USER = "postgres.ythxmkftubpwnlgxcdht" # User must include project ref for pooler
DB_PASS = "7CyGvtTLL2jXE5eA"
DB_PORT = "6543" # Transaction pooler port (or 5432 for session)

CSV_FILE = "Stock_History.csv"

def get_connection():
    try:
        conn = psycopg.connect(
            host=DB_HOST,
            dbname=DB_NAME,
            user=DB_USER,
            password=DB_PASS,
            port=DB_PORT
        )
        return conn
    except Exception as e:
        print(f"Connection failed: {e}")
        return None

def create_tables(conn):
    with conn.cursor() as cur:
        # Create stock_history table
        # Columns: ticker, date, price, ma_50, ma_200 (keeping simple for now)
        # Using double precision for prices
        cur.execute("""
            CREATE TABLE IF NOT EXISTS price_history (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ticker TEXT NOT NULL,
                date DATE NOT NULL,
                price DOUBLE PRECISION,
                ma_50 DOUBLE PRECISION,
                ma_200 DOUBLE PRECISION,
                UNIQUE(ticker, date)
            );
        """)
        
        # Create market_summary table for holding distinct tickers and latest status
        cur.execute("""
            CREATE TABLE IF NOT EXISTS market_summary (
                ticker TEXT PRIMARY KEY,
                last_updated TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
                latest_price DOUBLE PRECISION,
                trend_status TEXT, -- 'Bullish', 'Bearish'
                volatility_score DOUBLE PRECISION
            );
        """)
        
        # Create index on ticker for faster lookup
        cur.execute("CREATE INDEX IF NOT EXISTS idx_price_history_ticker ON price_history(ticker);")
        cur.execute("CREATE INDEX IF NOT EXISTS idx_price_history_date ON price_history(date);")
        
        conn.commit()
        print("Tables created successfully.")

def seed_data(conn):
    print(f"Reading {CSV_FILE}...")
    try:
        df = pd.read_csv(CSV_FILE)
    except FileNotFoundError:
        print(f"Error: {CSV_FILE} not found.")
        return

    # Standardize column names
    # CSV has: Date, Price, Volume, % Price Change, 50d MA, 200d MA, id, Ticker
    # We want: date, price, ma_50, ma_200, ticker
    
    # Rename for easier handling
    df.rename(columns={
        'Date': 'date',
        'Price': 'price',
        '50d MA': 'ma_50',
        '200d MA': 'ma_200',
        'Ticker': 'ticker'
    }, inplace=True)
    
    # Convert date
    df['date'] = pd.to_datetime(df['date']).dt.date
    
    # Select columns
    data_to_insert = df[['ticker', 'date', 'price', 'ma_50', 'ma_200']]
    
    # Replace NaN with None for SQL insertion
    data_to_insert = data_to_insert.where(pd.notnull(data_to_insert), None)
    
    print(f"Preparing to insert {len(data_to_insert)} rows...")
    
    with conn.cursor() as cur:
        # We use execute_batch or copy for speed. Copy is fastest.
        # Let's use copy.
        
        with cur.copy("COPY price_history (ticker, date, price, ma_50, ma_200) FROM STDIN") as copy:
            for _, row in data_to_insert.iterrows():
                copy.write_row((row['ticker'], row['date'], row['price'], row['ma_50'], row['ma_200']))
        
        conn.commit()
        print("Data seeded into 'price_history'.")
        
        # Now populate market_summary with distinct tickers
        cur.execute("""
            INSERT INTO market_summary (ticker, last_updated)
            SELECT DISTINCT ticker, NOW() FROM price_history
            ON CONFLICT (ticker) DO NOTHING;
        """)
        conn.commit()
        print("Market summary initialized.")

def main():
    conn = get_connection()
    if conn:
        create_tables(conn)
        seed_data(conn)
        conn.close()
    else:
        print("Failed to connect to database.")

if __name__ == "__main__":
    main()
